export const paths = {
  login: '/login',
  register: '/register',
  products: '/products',
  productDetail: (id = ':id') => `/products/${id}`,
  cart: '/cart',
  checkout: '/checkout',
  orders: '/orders',
  adminProducts: '/admin/products',
  adminOrders: '/admin/orders',
  paymentResult: '/payment/result',
  chat: '/chat',
  documents: '/documents',
  report: '/report',
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
  adminChat: '/admin/chat',
  customerChat: '/customer-chat',
};
